/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        // Semantic tokens — auto-switch via CSS variables
        primary: "rgb(var(--color-accent) / <alpha-value>)",
        "primary-light": "rgb(var(--color-accent-light) / <alpha-value>)",
        "bg-light": "rgb(var(--color-bg) / <alpha-value>)",
        "bg-secondary": "rgb(var(--color-bg-secondary) / <alpha-value>)",
        "bg-chat": "rgb(var(--color-bg-chat) / <alpha-value>)",
        "bg-card": "rgb(var(--color-bg-card) / <alpha-value>)",
        "bg-input": "rgb(var(--color-bg-input) / <alpha-value>)",
        "bg-hover": "rgb(var(--color-bg-hover) / <alpha-value>)",
        "nav-light": "rgb(var(--color-bg-nav) / <alpha-value>)",
        "border-light": "rgb(var(--color-border) / <alpha-value>)",
        "border-subtle": "rgb(var(--color-border-light) / <alpha-value>)",
        divider: "rgb(var(--color-divider) / <alpha-value>)",
        "text-main": "rgb(var(--color-text-primary) / <alpha-value>)",
        "text-muted": "rgb(var(--color-text-secondary) / <alpha-value>)",
        "text-hint": "rgb(var(--color-text-hint) / <alpha-value>)",
        "text-inverse": "rgb(var(--color-text-inverse) / <alpha-value>)",
        "ios-gray": "rgb(var(--color-bg-input) / <alpha-value>)",
        "bubble-user": "rgb(var(--color-bubble-user) / <alpha-value>)",
        "bubble-ai": "rgb(var(--color-bubble-ai) / <alpha-value>)",
        "accent-green": "rgb(var(--color-accent-green) / <alpha-value>)",
        success: "rgb(var(--color-accent-green) / <alpha-value>)",
        warning: "rgb(var(--color-warning) / <alpha-value>)",
        error: "rgb(var(--color-danger) / <alpha-value>)",
        chevron: "rgb(var(--color-chevron) / <alpha-value>)",
        "search-icon": "rgb(var(--color-search-icon) / <alpha-value>)",
        "section-header": "rgb(var(--color-section-header) / <alpha-value>)",
        "switch-track": "rgb(var(--color-switch-track) / <alpha-value>)",
        // Static decorative colors (same in both themes)
        "tag-reasoning": "#FFF8E1",
        "tag-reasoning-text": "#FF6F00",
        "tag-vision": "#E8F5E9",
        "tag-vision-text": "#1B5E20",
        "tag-tools": "#F3E5F5",
        "tag-tools-text": "#4A148C",
        "tag-coding": "#E8EAF6",
        "tag-coding-text": "#1A237E",
        "tag-context": "#FFF3E0",
        "tag-context-text": "#E65100",
      },
      fontFamily: {
        display: ["Inter"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
